version: "3.8"
services:
  fastapi:
    build: 
      context: "./fastapi-services"
      dockerfile: Dockerfile.debug
    ports:
      - "8124:8124"
      - "5678:5678"
    volumes:
      - type: bind
        source: ./fastapi-services
        target: /app
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - /fastapi-services/.env
    networks:
      - my-shared-network
networks:
  my-shared-network:
    driver: bridge